# Generated by Django 2.1.7 on 2019-03-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190307_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_brief',
            new_name='goods_brief',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_desc',
            new_name='goods_desc',
        ),
    ]
