# Generated by Django 2.1.7 on 2019-03-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190316_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='image',
            new_name='images',
        ),
    ]
