# Generated by Django 2.1.7 on 2019-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190316_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否新品'),
        ),
    ]
