# Generated by Django 2.1.7 on 2019-03-16 17:38

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20190316_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', help_text='品牌描述', null=True, verbose_name='品牌描述'),
        ),
    ]
