# Generated by Django 2.1.7 on 2019-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20190316_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_sn',
            field=models.CharField(blank=True, default='', help_text='商品唯一货号', max_length=20, null=True, verbose_name='商品唯一货号'),
        ),
    ]
