# Generated by Django 2.1.7 on 2019-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20190316_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.CharField(blank=True, default='', help_text='商品简介', max_length=500, null=True, verbose_name='商品简介'),
        ),
    ]
