# Generated by Django 2.1.7 on 2019-03-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190318_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer',
            new_name='signer_name',
        ),
    ]
