# Generated by Django 2.1.7 on 2019-03-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190318_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='singer_mobile',
            field=models.CharField(default='', max_length=100, verbose_name='签收人电话'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='定单'),
        ),
    ]
