# Generated by Django 2.1.7 on 2019-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190318_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='singer_mobile',
            field=models.CharField(default='', max_length=50, verbose_name='签收人电话'),
        ),
    ]
