# Generated by Django 2.1.7 on 2019-03-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
    ]
