# Generated by Django 2.1.7 on 2019-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190315_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=100, verbose_name='邮箱'),
        ),
    ]
