# Generated by Django 2.1.7 on 2019-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190315_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
    ]
