# Generated by Django 2.1.7 on 2019-03-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190317_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=10, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(default='', max_length=15, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=10, verbose_name='省份'),
        ),
    ]
